# Root
GET http://localhost:12345 HTTP/1.1

####

# List users
GET http://localhost:12345/users HTTP/1.1

###

# Create user
POST http://localhost:12345/users HTTP/1.1
Content-Type: application/json

{
    "name": "Lucas",
    "role": "Software Engineer"
}

###

# Try to create user with invalid name
POST http://localhost:12345/users HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "role": "Software Engineer"
}

###

# Get user by id
GET http://localhost:12345/users/6571c85d75b0520e362876b1

###

# Replace user
PUT http://localhost:12345/users/6571c85d75b0520e362876b1
Content-Type: application/json

{
    "name": "Lucas Mantovani",
    "role": "Sr. Software Engineer"
}

###

# Update user partially
PATCH http://localhost:12345/users/6571c85d75b0520e362876b1
Content-Type: application/json

{
    "role": "Tech Lead"
}

###

# Delete user
DELETE http://localhost:12345/users/6571c85d75b0520e362876b1

###

# Head get all users
HEAD http://localhost:12345/users

###

# Head get user
HEAD http://localhost:12345/users/6571c85d75b0520e362876b1

###

# Options /users
OPTIONS  http://localhost:12345/users

###

# Options /user
OPTIONS  http://localhost:12345/users/6571c85d75b0520e362876b1